name: deploy reusable workflow

on:
  workflow_call:
    inputs:
      namespace:
        type: string
        description: Namespace for deploy
        required: true
      environment:
        type: string
        description: Environment for deploy
        required: true
      application:
        type: string
        description: Application for deploy
        required: true
      override_config:
        type: string
        description: Override the instance build/deploy config
  workflow_dispatch:
    inputs:
      namespace:
        description: Namespaces for build
        required: true
        options:
          - appservices
        default: runner
        type: choice
      environment:
        description: Environment for build
        required: true
        options:
          - dev
          - stg
        default: dev
        type: choice
      application:
        type: choice
        description: Application for build
        required: true
        options:
          - frontend
          - backend
          - cron
        default: backend
      override_config:
        type: string
        description: Override the instance build/deploy config

env:
  DEPLOY_KEY: "${{ inputs.application }}__${{ inputs.namespace }}.${{ inputs.environment }}"
  WORKING_DIRECTORY: "/tmp"  # Replace with actual path
  HELM_FILE_PATH: "/opt"  # Replace with actual path
  ECR_REGISTRY: "your-ecr-registry-url"  # Replace with your actual ECR registry URL
  ECR_REPOSITORY: "your-repository-name"  # Replace with your actual repository name

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Helm diff
        run: |
          echo "cd ${{ env.WORKING_DIRECTORY }}/${{ env.HELM_FILE_PATH }}"
          echo "helmfile --namespace ${{ inputs.namespace }} -e ${{ inputs.environment }} diff --set MIGRATIONS=${{ toJSON(env.MIGRATIONS || false) }} --set NAMESPACE=${{ inputs.namespace }} --set DOCKER_IMAGE=${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ inputs.application }}.${{ inputs.namespace }}.${{ inputs.environment }}"
      
      - name: Get current release version
        run: |
          PREVIOUS_VERSION=release-1
          # $(helm ls --namespace ${{ inputs.namespace }} -q | tail -n 1)
          echo "PREVIOUS_VERSION=${PREVIOUS_VERSION}" >> $GITHUB_ENV  # Set the PREVIOUS_VERSION as environment variable for future steps

      - name: Helm install
        continue-on-error: true
        run: |
          echo "cd ${{ env.WORKING_DIRECTORY }}/${{ env.HELM_FILE_PATH }}"
          echo "helmfile --namespace ${{ inputs.namespace }} -e ${{ inputs.environment }} sync --set MIGRATIONS=${{ toJSON(env.MIGRATIONS || false) }} --set NAMESPACE=${{ inputs.namespace }} --set DOCKER_IMAGE=${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ inputs.application }}.${{ inputs.namespace }}.${{ inputs.environment }}"

  rollback:
    runs-on: ubuntu-latest
    needs: deployment
    if: failure()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Rollback to previous release
        run: |
          echo "cd ${{ env.WORKING_DIRECTORY }}/${{ env.HELM_FILE_PATH }}"
          echo "helmfile --namespace ${{ inputs.namespace }} -e ${{ inputs.environment }} sync --set DOCKER_IMAGE=${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.PREVIOUS_VERSION }}"
