name: MP dev auto deploy

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
  workflow_dispatch:

env:
  KUBECTL_VERSION: '1.22.13'
  ENVIRONMENT: dev

jobs:
  deployment:
    strategy:
      matrix:
        environment: [dev]
        application: ["frontend", "backend", "cron"]  
        namespace: ["appservices"]
    steps:
      - uses: ./.github/workflows/deployment.yml
        with:
          namespace: ${{ matrix.namespace }}
          environment: ${{ matrix.environment }}
          application: ${{ matrix.application }}
          override_config: ""
