# .github/workflows/dev.yml
name: MP dev auto deploy

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
  workflow_dispatch:

jobs:
  call-deployment-workflow:
    runs-on: ubuntu-latest  # Define your runner for the matrix jobs
    strategy:
      matrix:
        namespace: [appservices]  # Multiple namespaces
        environment: [dev]  # Different environments
        application: [frontend, backend, cron]  # Multiple applications
    steps:
      uses: ./.github/workflows/deployment.yml
      with:
        namespace: ${{ matrix.namespace }}
        environment: ${{ matrix.environment }}
        application: ${{ matrix.application }}
        override_config: ""  # Optional input
