name: MP dev auto deploy

on:
  push:
    branches:
      - main

env:
  KUBECTL_VERSION: '1.22.13'
  ENVIRONMENT: dev

jobs:
  deployment:
    runs-on: self-hosted-on-demand
    strategy:
      matrix:
        environment: [dev]
        application: ["frontend", "backend", "cron"]
        namespace: ["appservices"] 
    uses: ./.github/workflows/deployment.yml
    with:
      namespace: ${{ matrix.namespace }}
      environment: ${{ matrix.environment }}
      application: ${{ matrix.application }}
