name: MP dev auto deploy

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
  workflow_dispatch:
jobs:
  deployment:
    strategy:
      matrix:
        environment: [dev]
        application: ["frontend", "backend", "cron"]  
        namespace: ["appservices"]
    steps:
    - uses: ./.github/workflows/deployment.yml
      with:
        namespace: runner
        environment: dev
        application: backend
        override_config: ""