name: Dev auto Deploy

on:
  push:
    branches:
    - '*'

env:
  KUBECTL_VERSION: '1.22.13'
  ENVIRONMENT: dev

jobs:
  deployment:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev]
        application: ["frontend", "backend", "cron"]  
        namespace: ["appservices"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4   
      - uses: ./.github/workflows/deployment.yml
        with:
          namespace: ${{ matrix.namespace }}
          environment: ${{ matrix.environment }}
          application: ${{ matrix.application }}
